# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af64e63ebe5eef519d68c7217b7f686165aee5de406e7c9b15ef21897e45cc5125cddd238c676b751bc9ab359ef56fc5fe07e3e93b607bfa25aae964a3f04c3d

test:
  secret_key_base: f8717cb4cdb31b45942663cf73780265a9d03d82182a8cf869239955c5aa64d29912a46dac41a29bb5bec49122542cfc06d7af223b61b2ebad2e42d712587b3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
